language: java
jdk:
  - oraclejdk8
sudo: false
install: true
addons:
  sonarqube:
    organization: "dansiviter-github"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -X
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
