language: java
jdk: oraclejdk8
sudo: false
install: true
cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"